# This script was used to make dotplots in the manuscript that were used as scorecards. Two R packages, Seurat and ggplot2, need to be loaded.
# Each dotplot was generated by two parts of codes: 1) a list of genes, 2) the DotPlot function to plot the genes.
# The Dotplot function requires the Seurat object ("sample" in the code), the list of genes, and a parameter specifying how the cells should be grouped.
# The cells can be grouped by cluster identities or library identities by setting the group.by parameter to "idents" or "orig.ident", respectively.
# The normalized expression values for the genes in the score card can be extracted using the GetAssayData function. An example is shown in line 12 and 13.



AGM_cell_type = c("CD34","PECAM1","CDH5","PTPRC","SPN","THY1","PROCR","ACE","MLLT3","HLF","HOXA7","HOXA9","C1QA","LY86","GYPA","TFRC","PDGFRA","COL1A1","EPCAM","AFP")
DotPlot(sample, features=AGM_cell_type, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))
expression_data = as.matrix(GetAssayData(sample)[AGM_cell_type,])
View(expression_data)



Nascent_HSC = c("RUNX1","MLLT3","HOXA9","MECOM","HLF","SPINK2","MYB","GFI1","STAT5A","ZBTB16","HOPX","GATA2","GBP4","ITGA2B","KCNK17","SVOPL","C2orf88","SELP","CD82","ITGA4","GP9","TMEM163","RAB27B","SMIM24","GMPR","PDLIM1","ALDH1A1","NRGN","CCDC173","CXCL3","CYTL1","PRSS57","ANGPT1","CD34","PECAM1","CDH5","ECSCR.1","CALCRL","PROCR","ESAM","TIE1","EMCN")
DotPlot(sample, features=AGM_cell_type, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



Cell_identity_AGM = c("CDH5","KDR","TIE1","APLNR","NRP2","GJA5","CXCR4",
               "RUNX1","PTPRC","SPN",
               "C1QA","CD14","LYVE1","LYZ","RNASE2",
               "HLF","GFI1","MYB","MYCN",
               "COL1A1","PDGFRA","CXCL12","POSTN","PTN","PAX1","SOX9","HAND1","NKX2−3","DCN","ALDH1A2","COL14A1","CRABP1","LUM","PAX3","TBX5","HAND2","REN","GATA3","ACTC1","ACTA2","NPHS2","DSC1","NPHS1",
               "EPCAM","AFP","FGB","APOA1","MAL","CALB1",
               "HBE1","HBZ","GYPA",
               "MKI67","TOP2A","AURKB")
DotPlot(sample, features=Cell_identity_AGM, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



Hema_cell_identity_AGM = c("RUNX1","SPN","PTPRC",
                  "HOXA9","MLLT3","HLF","MYB","GATA2","MECOM",
                  "CD3E","CCR7","IL7R"," LTB","CD69","CD7",
                  "LYZ","S100A8","FCGR3A","MPO","AZU1","RNASE3",
                  "C1QA","C1QB","C1QC","LYVE1","RNASE1","CD14",
                  "KDR","NT5E","NPR1","SOX7","VWF","CDH5", "EDNRA","TWIST1","PDGFRA","COL1A1","COL3A1","LUM",
                  "MKI67","AURKB")
DotPlot(sample, features=Hema_cell_identity_AGM, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



Liver_SPINK2_genes = c("PSMB9","HLA-DRB1","CX3CR1","IFI35","CD48","PIK3AP1","NCF1","HLA-DMB","LTB","HDAC9","SERPINF1","BLNK","MX1","BANK1","IL2RG","LGMN","KIF17","KIAA0930","AGR2","IL7R","MRC1","PKIB","DHRS9","SPNS3","JCHAIN","PAG1","TLR10","PHACTR1","HLA-DRA","CTSW","GAS6","CD180","CYBB","IRF8","ITGB7","SAMHD1","CXorf21","LY86","LAT2","ACY3")
DotPlot(sample, features=Liver_SPINK2_genes, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



HSC_transcription_factors = c("RUNX1","SPI1","TAL1","LYL1","LMO2","MYC","ETV6","BCL11A","GFI1","GFI1B","GATA2","GATA3","MYB","MLLT3","HLF","HOXA7","HOXA9","PBX1","PRDM16","MECOM")
DotPlot(sample, features=HSC_transcription_factors, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



HSC_maturation = c("CDH5","MEIS2","RUNX1T1","ESAM","PLVAP","SELP","ITGA2B","GP9","RAB27B","GMPR","GFI1","GBP4","MECOM","IGFBP2","HMGA2","LIN28B","IL3RA","IL6R","IL11RA","IFNAR1","IFNAR2","IFNGR1","CSF1R","CSF2RA","MKI67","TOP2A","AURKB","HLA-A","HLA-B","HLA-C","HLA-E","B2M","HLA-DMA","HLA-DPB1","HLA-DRA","HLA-DQA1","HLA-DPA1","HLA-DQB1","MLLT3","HLF","MALAT1","MSI2","EVI2B","SOCS2","HEMGN","HOPX","SPINK2","CD52","SELL","PROM1")
DotPlot(sample, features=HSC_maturation, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



HOXA/HOXB_genes = c("HOXA1","HOXA2","HOXA3","HOXA4","HOXA5","HOXA6","HOXA7","HOXA9","HOXA10","HOXA11","HOXB2","HOXB3","HOXB4","HOXB5","HOXB6","HOXB7","HOXB8","HOXB9")
DotPlot(sample, features=HOXA/HOXB_genes, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



HSC_surface_markers = c("PTPRC","SPN","ITGA2B","CDH5","CD34","THY1","VNN2","ITGAM","EMCN","PROCR","IL3RA","SELP","ACE","PROM1","HLA-DRA")
DotPlot(sample, features=HSC_surface_markers, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



EHT_scorecard = c("CDH5","RUNX1","PTPRC", "SPN","CD44","ITGA2B","HLF","GFI1","MLLT3","HOXA9","MKI67",
                 "NRP2","NR2F2",
                 "GJA4","HEY1","DLL4","CXCR4","SOX17","SMAD6","GJA5","HES4","MECOM",
                 "NID2","PRND","ESM1","PDGFB",
                 "PALMD","TMEM100","EDN1","LTBP4","HEY2",
                 "SULF1","IL33","CYP26B1",
                 "ADGRG6","COL23A1","GATA6","BMX","TMCC3","DKK1","AGTR2",
                 "FBN2","ELN","ALDH1A1","NKX2-3","PROCR","GATA3","GBP4",
                 "MYCN","KCNK17",
                 "MYB","STAT5A","SMIM24","RAB27B","SPINK2")
DotPlot(sample, features=EHT_scorecard, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



EHT_pseudotime = c("KDR","FLT4","ROCK2","LAMA4","TJP1","CAV2","CAV1","ITGA1","ITGA9",
                   "RUNX1","CEBPB","MLLT3","DOT1L","AFF1","ETV6","MYCN","REL",
                   "GFI1","GFI1B",
                   "CD44","ITGA4","ITGA2B","CD33","GP9","KIT")
DotPlot(sample, features=EHT_pseudotime, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



Proliferation_metabolism = c("PCNA","MCM2","MCM7","CCNB1","CDK4","CDK2","TP53","MKI67",
                             "GAPDH","ENO1","PKM","LDHA","LDHB",
                             "TPI1","FH","MDH1","IDH2","SDHB")
DotPlot(sample, features=Proliferation_metabolism, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



Signaling = c("TGFBR2","BMPR2","TGFB1","ID1","ID3","FOXO1","SMAD6","SMAD7","SMURF2","BMPER",
               "NOTCH1","NOTCH3","NOTCH4","DLL4","JAG1","JAG2","HES1","HEY1","HEY2","HES4",
               "CTNNB1","LRP5","LRP6","FZD6","TCF3","TCF4","TCF7L1","TCF7L2","LEF1","DKK1","DKK2","CTBP1","CTBP2","NLK",
               "ALDH1A1","ALDH1A2","CYP26B1","CYP27C1","CRABP1","CRABP2","RARA","RARB","RARG","RXRA","RXRB","RARRES2","GPRC5A","GPRC5B","GPRC5C","TGM2",
               "CSF2RA","CSF2RB","CSF3R","IL6R","IL27RA","STAT5A","JAK2","PIK3CD","PTPN2","PIM1")
DotPlot(sample, features=Signaling, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



HSPC_waves = c("CDH5","RUNX1","KCNK17","CD44","PTPRC","SPN","ITGA2B","LYVE1","HLF","SPINK2","RAB27B","SMIM24","MYB",
               "RUNX1T1","MECOM","MLLT3","NKX2-3","EAF2","BCL11A",
               "PROCR","EMCN","GBP4","CD74","ACE","ITGA4","KIT",
               "LIN28A","DDIT4","SLC2A3","RGS16","FGF23","GAD1","MT1E","STXBP6",
               "HOXA7","HOXA9","HOXB7","HOXB9")
DotPlot(sample, features=HSPC_waves, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))



Endo_waves = c("NRP2","APLNR","NR2F2",
               "GJA4","GJA5","DLL4","EFNB2","CXCR4",
               "NOTCH1","NOTCH3","NOTCH4","JAG1","JAG2","HES1","HEY1","HEY2","HES4",
               "EDN1","TMEM100","IL11RA","IL3RA","ADGRG6","LTBP4",
               "SULF1","IL33","AGTR2","DKK1","DKK2",
               "SMAD6","SMAD7",
               "ALDH1A1","ALDH1A2","CYP26B1",
               "LDHA","ENO1","ALDOA","GAPDH")
DotPlot(sample, features=Endo_waves, cols=c("grey90","red3"), group.by="idents") +
  coord_flip() + theme(axis.text.x=element_text(angle=45, hjust=1))

